// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApRl-rdOxyI7LJKtHItjQfxH13voW1rcY',
    appId: '1:1085663313313:web:6cd55b5787c5c693819fe0',
    messagingSenderId: '1085663313313',
    projectId: 'firebase-login-time',
    authDomain: 'fir-login-time.firebaseapp.com',
    storageBucket: 'firebase-login-time.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJiP3atZ0hVWS7IKVy8ptBhitiQgrHZEk',
    appId: '1:1085663313313:android:73edb68df31c90ba819fe0',
    messagingSenderId: '1085663313313',
    projectId: 'firebase-login-time',
    storageBucket: 'firebase-login-time.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIL6v5cxeXEi3nHXanpwvBNrnWnv-rQqk',
    appId: '1:1085663313313:ios:99258a66be381dff819fe0',
    messagingSenderId: '1085663313313',
    projectId: 'firebase-login-time',
    storageBucket: 'firebase-login-time.appspot.com',
    iosClientId: '1085663313313-u96g0ruqo90j0uvst3vht595h8etro32.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseLoginTime',
  );
}
